version: "3.9"
services:
  db:
    image: mariadb
    container_name: Data_Base
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - cangrownet
    ports:
      - "3031:3031"

  wordpress1:
    container_name: wordpress1
    depends_on:
    - nginx
    image: wordpress:latest
    volumes:
    - wordpress_data:/var/www/html
    ports:
    - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - cangrownet

  wordpress2:
    container_name: wordpress2
    depends_on:
    - nginx
    image: wordpress:latest
    volumes:
    - wordpress_data:/var/www/html
    ports:
    - "8001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - cangrownet

  nginx:
    image: nginx
    container_name: Nginx_LoadBalance
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
    - db
    networks:
      - cangrownet


volumes:
    db_data: {}
    wordpress_data: {}

networks:
  cangrownet:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.20.0.0/28"
                gateway: "172.20.0.1"
